main: main.o Add.o create.o delete.o menu.o modify.o myhead.h print.o search.o sort_link.o 注册登陆.o
	gcc -o main  -g main.o Add.o create.o delete.o menu.o modify.o myhead.h print.o search.o sort_link.o 注册登陆.o -lm
